name: Install Dotfile on macOS

on:
  push:
   branches:
     - "main"
  pull_request:

jobs:
  root-job:
    name: Install Dotfiles
    runs-on: linux-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Validate syntax
      run: bash -n *.sh

    - name: set up dotfile
      run: |
        sudo bash ./install.sh

    - name: Check Echo
      run: command -v fish && command -v brew && command -v wezterm
