name: Install Dotfile on macOS

on:
  push:
   branches:
     - "main"
  pull_request:

jobs:
  install-dotfiles:
    name: Install Dotfiles
    runs-on: macos-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Validate syntax
      run: bash -n *.sh

    - name: set up dotfile
      run: bash ./install.sh
